---
output: html_document
---

# Introducción

En Chile, a partir del año 2006 se llevaron a cabo una serie de protestas exigiendo reformas educativas. Dichas protestas las denominaron "Revolución de los pingüinos", debido al uniforme escolar que se utiliza en el país. Entre las principales demandas de las manifestaciones se encuentran prohibir el lucro en la educación privada y que el Estado brinde educación pública, gratuita y de calidad (Fuente: BBC). Fruto de estas protestas, en el año 2011 se crea la Agencia de Calidad de la Educación.

Este servicio tiene como objetivo "evaluar, informar y orientar al sistema educativo para contribuir al mejoramiento de la calidad y equidad de las oportunidades educativas de todos los estudiantes de Chile" (Fuente: Agencia de Calidad de la Educación). Con respecto al primer objetivo, se puede mencionar que en Chile se realizan diferentes pruebas para medir los aprendizajes en diversas áreas curriculares como, por ejemplo, Compresión de Lectura, Matemática o Ciencias Naturales. Algunas de estas evaluaciones pueden ser nacionales, como el Simce, o parte de estudios internacionales como lo son las pruebas PISA, PIRLS, TIMSS, ERCE, entre otras. Otro aspecto relacionado con este objetivo es que, al evaluar a los estudiantes a nivel nacional, se puede medir el impacto de las reformas implementadas, o incluso, las inversiones realizadas para esta área, pues para los gobiernos es importante determinar cómo influye el dinero gastado en cada ministerio.

En este informe se investigará la relación entre los resultados de las pruebas internacionales PISA y el gasto en educación en Chile entre los años 2001 y 2018. Para ello se disponen datos sobre los resultados dichas evaluación, por categoría y año, en ese periodo, además del gasto público en educación del país de diferentes áreas, por ejemplo, según el nivel educacional.

El informe contiene cuatro secciones. La primera parte, se detallarán las pruebas PISA, en particular, las áreas de conocimiento que evalúan y cómo se interpretan los resultados obtenidos.  La segunda sección, se explicará las metodologías que se utilizaron para el desarrollo del informe, además se mostraran, brevemente, los datos utilizados. Luego, se mostrará los resultados obtenidos a partir del análisis. Por último, en la conclusión, se realizará una proyección para futuras pruebas PISA.